### PR TITLE
does not patch TMPE above version 11.1

### PR DESCRIPTION
**Pull request by kianzarrin**
see #649

works with all versions of TMPE.

### CODE REVIEW

**Comment by pcfantasy** [comment]
@kianzarrin 

I add some print blow：

DebugLog.LogToFileOnly("TMPE_Version = " + TMPE_Version.ToString());
if(TMPE_Version < new Version(11, 1)) {
                        DebugLog.LogToFileOnly("TMPE_Version < 11.1, so apply LC patch ");
}

Get result blow:

TMPE_Version = 1.0.7338.31077
TMPE_Version < 11.1, so apply LC patch 

Is it what you experted? I use 1806963141 TM:PE v11.0 LABS

**Comment by kianzarrin** [comment]
> 
> 
> @kianzarrin
> 
> I add some prints blow：
> 
> DebugLog.LogToFileOnly("TMPE_Version = " + TMPE_Version.ToString());
> if(TMPE_Version < new Version(11, 1)) {
> DebugLog.LogToFileOnly("TMPE_Version < 11.1, so apply LC patch ");
> }
> 
> Get results blow:
> 
> TMPE_Version = 1.0.7338.31077
> TMPE_Version < 11.1, so apply LC patch
> 
> Is it what you experted? I use 1806963141 TM:PE v11.0 LABS

Yes. Version used to be 1.0 but I changed it to 11.1 there is a work in progress about TMPE version management.

you might wanna test with this branch too https://github.com/kianzarrin/Cities-Skylines-Traffic-Manager-President-Edition/tree/649-csur-laneconnector

pull request for that branch is: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/684

**Comment by pcfantasy** [comment]
Thank you, it is OK now.

**Comment by aubergine10** [comment]
We will be releasing a TM:PE beta to LABS page that does not yet contain the CSUR updates. The beta will be versioned `11.1.0`

Please update CSUR to check for TM:PE version `11.1.1` or abvoe (which will contain the CSUR updates)

**Pull request merged**
