### PR TITLE
TM:PE 11.1.1 will contain the update

### PR DESCRIPTION
**Pull request by aubergine10**
A beta (11.1.0) is being pushed to LABS workshop page which does not yet contain the CSUR code; we need to get a bunch of other features out for users to test first.

11.1.1 should follow shortly after once we've had time to do full PR review.

Please let us know when this PR is merged and published to Steam Workshop so we can release the TM:PE 11.1.0 beta to LABS workshop without breaking CSUR compatibility.

Fixes krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/687

### CODE REVIEW

**Comment by aubergine10** [comment]
cc: @kianzarrin

**Comment by pcfantasy** [comment]
thanks

**Comment by aubergine10** [comment]
Is it now OK for TM:PE 11.1.0 to be pushed to LABS workshop?

**Comment by pcfantasy** [comment]
@aubergine10 

OK, I will also update CSUR ToolBox right now.

**Pull request merged**
